import type { PrismaClient } from '@prisma/client'
import { PaymentStatus } from '@prisma/client'
import { calculateNextPeriod, getDueDate, isOverdue } from '../utils/contractUtils.js'
import { logger } from '../logger.js'

/**
 * generateUnpaidRecords — runs daily to create UNPAID payment records
 * for the upcoming billing period. Skips RESIDENTIAL_SHORT and PARKING contracts.
 */
export async function generateUnpaidRecords(prisma: PrismaClient): Promise<void> {
    const contracts = await prisma.contract.findMany({
        where: {
            status: 'ACTIVE',
            deletedAt: null,
            rentalType: { notIn: ['RESIDENTIAL_SHORT', 'PARKING'] },
        },
        select: {
            id: true,
            organizationId: true,
            monthlyRent: true,
            paymentDay: true,
            fixedPaymentDay: true,
            gracePeriodDays: true,
            paymentTiming: true,
            startDate: true,
        },
    })

    for (const contract of contracts) {
        try {
            const today = new Date()
            // Pass day before 1st of current month so calculateNextPeriod returns the CURRENT period
            const dayBeforeCurrentMonth = new Date(today.getFullYear(), today.getMonth(), 1)
            dayBeforeCurrentMonth.setDate(dayBeforeCurrentMonth.getDate() - 1)
            const { periodStart, periodEnd, amount } = calculateNextPeriod(contract, dayBeforeCurrentMonth)
            const periodMonth = periodStart.getMonth() + 1
            const periodYear = periodStart.getFullYear()

            // Check if a record already exists for this period
            const existing = await prisma.payment.findFirst({
                where: {
                    contractId: contract.id,
                    periodMonth,
                    periodYear,
                    deletedAt: null,
                },
                select: { id: true },
            })

            if (!existing) {
                await prisma.payment.create({
                    data: {
                        contractId: contract.id,
                        organizationId: contract.organizationId,
                        amount: 0,
                        expectedAmount: amount,
                        status: 'UNPAID',
                        periodMonth,
                        periodYear,
                        periodStart,
                        periodEnd,
                        paymentDate: periodStart, // placeholder — overwritten when landlord records payment
                        paymentType: 'CASH',      // required field placeholder
                        isPenalty: false,
                        createdBy: null,           // system-generated by cron
                    } as never,
                })
                logger.info(`[BillingCron] Generated UNPAID for contract ${contract.id} period ${periodMonth}/${periodYear}`)
            }
        } catch (err) {
            logger.error(`[BillingCron] Failed to generate UNPAID for contract ${contract.id}:`, err)
        }
    }
}

/**
 * markOverduePayments — runs daily to mark UNPAID/PARTIAL payments as OVERDUE
 * when their due date has passed.
 */
export async function markOverduePayments(prisma: PrismaClient): Promise<void> {
    const pendingPayments = await prisma.payment.findMany({
        where: {
            status: { in: ['UNPAID', 'PARTIAL'] },
            deletedAt: null,
        },
        select: {
            id: true,
            periodMonth: true,
            periodYear: true,
            periodStart: true,
            periodEnd: true,
            contract: {
                select: {
                    paymentDay: true,
                    fixedPaymentDay: true,
                    gracePeriodDays: true,
                    paymentTiming: true,
                },
            },
        },
    })

    for (const payment of pendingPayments) {
        try {
            if (!payment.contract) continue
            if (!payment.periodMonth || !payment.periodYear) continue

            // Use stored periodStart/periodEnd if available (set by cron for fixedPaymentDay contracts)
            // otherwise reconstruct from periodMonth/periodYear (calendar month boundaries)
            const periodStart = payment.periodStart
                ?? new Date(payment.periodYear, payment.periodMonth - 1, 1)
            const periodEnd = payment.periodEnd
                ?? new Date(payment.periodYear, payment.periodMonth, 0) // last day of month

            const dueDate = getDueDate(payment.contract, periodStart, periodEnd)

            if (isOverdue(dueDate)) {
                await prisma.payment.update({
                    where: { id: payment.id },
                    data: { status: PaymentStatus.OVERDUE },
                })
                logger.warn(`[BillingCron] Payment ${payment.id} marked OVERDUE (due: ${dueDate.toISOString()})`)
            }
        } catch (err) {
            logger.error(`[BillingCron] Failed to check overdue for payment ${payment.id}:`, err)
        }
    }
}
