import type { PrismaClient } from '@prisma/client'
import { PaymentStatus, RenewalType } from '@prisma/client'
import { calculateNextPeriod, getDueDate, isOverdue } from '../utils/contractUtils.js'
import { logger } from '../logger.js'
import { writeAuditLog } from '../utils/audit.js'
import { sendRenewalWarning } from '../services/email.js'

/**
 * generateUnpaidRecords — runs daily to create UNPAID payment records
 * for the upcoming billing period. Skips RESIDENTIAL_SHORT and PARKING contracts.
 */
export async function generateUnpaidRecords(prisma: PrismaClient): Promise<void> {
    const contracts = await prisma.contract.findMany({
        where: {
            status: 'ACTIVE',
            deletedAt: null,
            rentalType: { notIn: ['RESIDENTIAL_SHORT', 'PARKING'] },
        },
        select: {
            id: true,
            organizationId: true,
            monthlyRent: true,
            paymentDay: true,
            fixedPaymentDay: true,
            gracePeriodDays: true,
            paymentTiming: true,
            startDate: true,
        },
    })

    for (const contract of contracts) {
        try {
            const today = new Date()
            // Pass day before 1st of current month so calculateNextPeriod returns the CURRENT period
            const dayBeforeCurrentMonth = new Date(today.getFullYear(), today.getMonth(), 1)
            dayBeforeCurrentMonth.setDate(dayBeforeCurrentMonth.getDate() - 1)
            const { periodStart, periodEnd, amount } = calculateNextPeriod(contract, dayBeforeCurrentMonth)
            const periodMonth = periodStart.getMonth() + 1
            const periodYear = periodStart.getFullYear()

            // Check if a record already exists for this period
            const existing = await prisma.payment.findFirst({
                where: {
                    contractId: contract.id,
                    periodMonth,
                    periodYear,
                    deletedAt: null,
                },
                select: { id: true },
            })

            if (!existing) {
                await prisma.payment.create({
                    data: {
                        contractId: contract.id,
                        organizationId: contract.organizationId,
                        amount: 0,
                        expectedAmount: amount,
                        status: 'UNPAID',
                        periodMonth,
                        periodYear,
                        periodStart,
                        periodEnd,
                        paymentDate: periodStart, // placeholder — overwritten when landlord records payment
                        paymentType: 'CASH',      // required field placeholder
                        isPenalty: false,
                        createdBy: null,           // system-generated by cron
                    } as never,
                })
                logger.info(`[BillingCron] Generated UNPAID for contract ${contract.id} period ${periodMonth}/${periodYear}`)
            }
        } catch (err) {
            logger.error(`[BillingCron] Failed to generate UNPAID for contract ${contract.id}:`, err)
        }
    }
}

/**
 * markOverduePayments — runs daily to mark UNPAID/PARTIAL payments as OVERDUE
 * when their due date has passed.
 */
export async function markOverduePayments(prisma: PrismaClient): Promise<void> {
    const pendingPayments = await prisma.payment.findMany({
        where: {
            status: { in: ['UNPAID', 'PARTIAL'] },
            deletedAt: null,
        },
        select: {
            id: true,
            periodMonth: true,
            periodYear: true,
            periodStart: true,
            periodEnd: true,
            contract: {
                select: {
                    paymentDay: true,
                    fixedPaymentDay: true,
                    gracePeriodDays: true,
                    paymentTiming: true,
                },
            },
        },
    })

    for (const payment of pendingPayments) {
        try {
            if (!payment.contract) continue
            if (!payment.periodMonth || !payment.periodYear) continue

            // Use stored periodStart/periodEnd if available (set by cron for fixedPaymentDay contracts)
            // otherwise reconstruct from periodMonth/periodYear (calendar month boundaries)
            const periodStart = payment.periodStart
                ?? new Date(payment.periodYear, payment.periodMonth - 1, 1)
            const periodEnd = payment.periodEnd
                ?? new Date(payment.periodYear, payment.periodMonth, 0) // last day of month

            const dueDate = getDueDate(payment.contract, periodStart, periodEnd)

            if (isOverdue(dueDate)) {
                await prisma.payment.update({
                    where: { id: payment.id },
                    data: { status: PaymentStatus.OVERDUE },
                })
                logger.warn(`[BillingCron] Payment ${payment.id} marked OVERDUE (due: ${dueDate.toISOString()})`)
            }
        } catch (err) {
            logger.error(`[BillingCron] Failed to check overdue for payment ${payment.id}:`, err)
        }
    }
}

/**
 * checkRenewalWarnings — runs daily to send renewal warning emails for contracts
 * with autoRenewal=true that are approaching their endDate.
 */
export async function checkRenewalWarnings(prisma: PrismaClient): Promise<void> {
    const today = new Date()

    const contracts = await prisma.contract.findMany({
        where: {
            status: 'ACTIVE',
            autoRenewal: true,
            renewalNoticeDays: { not: null },
            deletedAt: null,
        },
        select: {
            id: true,
            organizationId: true,
            number: true,
            endDate: true,
            renewalNoticeDays: true,
            tenant: { select: { firstName: true, lastName: true, companyName: true, tenantType: true } },
            property: { select: { name: true } },
            organization: {
                select: {
                    users: {
                        where: { role: 'OWNER', isActive: true },
                        select: { id: true, email: true },
                        take: 1,
                    },
                },
            },
        },
    })

    for (const contract of contracts) {
        try {
            if (!contract.renewalNoticeDays) continue

            const noticeDays = contract.renewalNoticeDays
            const warningDate = new Date(contract.endDate)
            warningDate.setDate(warningDate.getDate() - noticeDays)

            // Only trigger when today is within the warning window and contract hasn't ended
            if (today < warningDate || today >= contract.endDate) continue

            // Check if warning was already sent for this renewal cycle
            // (i.e. a warning was created after the warning window opened)
            const windowStart = new Date(contract.endDate.getTime() - noticeDays * 24 * 60 * 60 * 1000)
            const existingWarning = await prisma.auditLog.findFirst({
                where: {
                    entityType: 'Contract',
                    entityId: contract.id,
                    action: 'CONTRACT_RENEWAL_WARNING',
                    createdAt: { gte: windowStart },
                },
                select: { id: true },
            })
            if (existingWarning) continue

            const owner = contract.organization.users[0]

            // Write audit log FIRST (dedup key), then send email
            if (owner?.id) {
                await writeAuditLog(prisma, {
                    organizationId: contract.organizationId,
                    userId: owner.id,
                    action: 'CONTRACT_RENEWAL_WARNING',
                    entityType: 'Contract',
                    entityId: contract.id,
                    metadata: {
                        endDate: contract.endDate.toISOString(),
                        renewalNoticeDays: noticeDays,
                    },
                })
            }

            if (owner?.email) {
                const tenantName = contract.tenant.tenantType === 'fiziki'
                    ? `${contract.tenant.firstName || ''} ${contract.tenant.lastName || ''}`.trim()
                    : contract.tenant.companyName || ''

                await sendRenewalWarning(owner.email, {
                    contractNumber: contract.number,
                    tenantName,
                    propertyName: contract.property.name,
                    endDate: contract.endDate.toISOString().slice(0, 10),
                    renewalNoticeDays: noticeDays,
                    contractId: contract.id,
                })
            }

            logger.info(`[BillingCron] Sent renewal warning for contract ${contract.id}`)
        } catch (err) {
            logger.error(`[BillingCron] Failed renewal warning for contract ${contract.id}:`, err)
        }
    }
}

/**
 * processAutoRenewals — runs daily to auto-renew expired contracts with autoRenewal=true.
 */
export async function processAutoRenewals(prisma: PrismaClient): Promise<void> {
    const today = new Date()

    const contracts = await prisma.contract.findMany({
        where: {
            status: 'ACTIVE',
            autoRenewal: true,
            endDate: { lt: today },
            deletedAt: null,
        },
        select: {
            id: true,
            organizationId: true,
            number: true,
            startDate: true,
            endDate: true,
            renewalType: true,
            organization: {
                select: {
                    users: {
                        where: { role: 'OWNER', isActive: true },
                        select: { id: true },
                        take: 1,
                    },
                },
            },
        },
    })

    for (const contract of contracts) {
        try {
            // Check if this contract was already auto-renewed in the current cycle
            const existingRenewal = await prisma.auditLog.findFirst({
                where: {
                    entityType: 'Contract',
                    entityId: contract.id,
                    action: 'CONTRACT_AUTO_RENEWED',
                    createdAt: { gte: contract.endDate },
                },
                select: { id: true },
            })
            if (existingRenewal) continue

            const oldEndDate = new Date(contract.endDate)
            let newEndDate: Date

            if (contract.renewalType === RenewalType.MONTHLY) {
                newEndDate = new Date(oldEndDate)
                newEndDate.setDate(newEndDate.getDate() + 30)
            } else {
                // SAME_PERIOD (default)
                const durationMs = new Date(contract.endDate).getTime() - new Date(contract.startDate).getTime()
                const durationDays = Math.floor(durationMs / (1000 * 60 * 60 * 24))
                newEndDate = new Date(oldEndDate)
                newEndDate.setDate(newEndDate.getDate() + durationDays)
            }

            const owner = contract.organization.users[0]

            await prisma.$transaction(async (tx) => {
                await tx.contract.update({
                    where: { id: contract.id },
                    data: { endDate: newEndDate },
                })

                if (owner?.id) {
                    await writeAuditLog(tx, {
                        organizationId: contract.organizationId,
                        userId: owner.id,
                        action: 'CONTRACT_AUTO_RENEWED',
                        entityType: 'Contract',
                        entityId: contract.id,
                        metadata: {
                            oldEndDate: oldEndDate.toISOString(),
                            newEndDate: newEndDate.toISOString(),
                            renewalType: contract.renewalType ?? 'SAME_PERIOD',
                        },
                    })
                }
            })

            logger.info(`[BillingCron] Auto-renewed contract ${contract.id} → ${newEndDate.toISOString()}`)
        } catch (err) {
            logger.error(`[BillingCron] Failed auto-renewal for contract ${contract.id}:`, err)
        }
    }
}

/**
 * resetDailyTickerCounts — runs at midnight to reset todayCount for all ticker slots.
 */
export async function resetDailyTickerCounts(prisma: PrismaClient): Promise<void> {
    await prisma.tickerSlot.updateMany({
        data: { todayCount: 0, todayDate: new Date() },
    })
    logger.info('[BillingCron] Ticker daily counts reset')
}
